### PR TITLE
Healpix SHTs

### PR DESCRIPTION
**Pull request by xzackli**
(work in progress)

I've added the geom_info structures and wrapped a helper for weighted Healpix rings. I'm basing the code for calling LibSharp on the NaMaster implementation.

This is towards doing SHTs on Healpix maps, i.e. https://github.com/ziotom78/Healpix.jl/issues/20

### CODE REVIEW

**Comment by xzackli** [comment]
@ziotom78 I'm stuck on the substantive bit -- the function definition for [sharp_execute](https://gitlab.mpcdf.mpg.de/mtr/libsharp/blob/master/libsharp2/sharp.h#L204) asks for the alms and maps as `complex double **` and `double **` respectively, do you know how to do this correctly with Ref and Ptr? My naive attempt leads to [segfaults](https://github.com/xzackli/Libsharp.jl/blob/master/examples/test_geom.jl#L19).

**Comment by xzackli** [comment]
I've written a quick reference code in C to make sure the issue isn't on the understanding LibSharp side, but on the understanding Julia side.

https://github.com/xzackli/example_libsharp_C/blob/master/main.c

**Comment by ziotom78** [comment]
Hi @xzackli , thanks a lot for your work! Unfortunately, I am currently not very responsive in these days, because of the COVID-19 emergency; once I have some time, I'll review your PR and fix the issue with segfaults and code coverage.

**Comment by xzackli** [comment]
Of course, please take your time and focus on the important stuff during this crisis! I will try to fix this PR up, I think I know roughly what needs to be done.

**Comment by ziotom78** [comment]
@xzackli , this looks great! Do you plan to add more significant features, or is this PR nearly ready to be submitted? If it is so, may you please add proper tests to the `test/` folder, to improve code coverage? If you do not have time, I will do it in the next weeks.

**Comment by xzackli** [comment]
I believe this PR is ready for submission. Once we merge this, I could also PR something like `examples/healpix_example.jl` into Healpix.jl for `map2alm` and `alm2map` to resolve the original issue.

I'm looking forward to your comments! But again, please take your time -- it's a crazy world out there.

**Comment by ziotom78** [comment]
Great job, thanks a lot @xzackli !

I would like to provide a high-level interface to this library in Healpix.jl, similar to the one provided by healpy in [sphtfunc.py](https://github.com/healpy/healpy/blob/master/healpy/sphtfunc.py). But first I must register this package in the official Julia Registry, so that Healpixjl can list Libsharp.jl as a dependency.

**Pull request merged**
